# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "plana-tf-state"
    dynamodb_table = "tf-lock-table"
    encrypt        = false
    key            = "./plana.tfstate"
    region         = "eu-central-1"
  }
}
